src/Entity/Figures.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\FiguresRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=FiguresRepository::class)
 *
 * @UniqueEntity("name", message = "Un nom de figure existe déjà")
 */
class Figures
{
    const PATH_IMAGE = '\images\figures\\';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="figures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=FiguresGroups::class, inversedBy="figures")
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotNull(
     *     message = "Un groupe est obligatoire pour cette figure"
     * )
     */
    private $figure_group;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotNull(
     *      message = "Le nom de la figure est obligatoire"
     * )
     *
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     *
     * @Assert\NotNull(
     *      message = "La déscription est obligatoire"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity=FiguresImages::class, mappedBy="figure", cascade={"persist"}, orphanRemoval=true)
     */
    private $figuresImages;

    /**
     * @ORM\OneToMany(targetEntity=FiguresVideos::class, mappedBy="figure", cascade={"persist"}, orphanRemoval=true)
     */
    private $figuresVideos;

    /**
     * @ORM\OneToMany(targetEntity=Discussions::class, mappedBy="figure", orphanRemoval=true, cascade={"persist"})
     */
    private $discussions;
    
    /**
     * Path to image
     *
     * @var string
     */
    private $path_image;

    public function __construct()
    {
        $this->figuresImages = new ArrayCollection();
        $this->figuresVideos = new ArrayCollection();
        $this->discussions = new ArrayCollection();

        date_default_timezone_set('Europe/Paris');
        $this->created_at = new DateTimeImmutable();
        $this->updated_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFigureGroup(): ?FiguresGroups
    {
        return $this->figure_group;
    }

    public function setFigureGroup(?FiguresGroups $figure_group): self
    {
        $this->figure_group = $figure_group;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, FiguresImages>
     */
    public function getFiguresImages(): Collection
    {
        return $this->figuresImages;
    }

    public function addFiguresImage(FiguresImages $figuresImage): self
    {
        if (!$this->figuresImages->contains($figuresImage)) {
            $this->figuresImages[] = $figuresImage;
            $figuresImage->setFigure($this);
        }

        return $this;
    }

    public function removeFiguresImage(FiguresImages $figuresImage): self
    {
        if ($this->figuresImages->removeElement($figuresImage)) {
            // set the owning side to null (unless already changed)
            if ($figuresImage->getFigure() === $this) {
                $figuresImage->setFigure(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, FiguresVideos>
     */
    public function getFiguresVideos(): Collection
    {
        return $this->figuresVideos;
    }

    public function addFiguresVideo(FiguresVideos $figuresVideo): self
    {
        if (!$this->figuresVideos->contains($figuresVideo)) {
            $this->figuresVideos[] = $figuresVideo;
            $figuresVideo->setFigure($this);
        }

        return $this;
    }

    public function removeFiguresVideo(FiguresVideos $figuresVideo): self
    {
        if ($this->figuresVideos->removeElement($figuresVideo)) {
            // set the owning side to null (unless already changed)
            if ($figuresVideo->getFigure() === $this) {
                $figuresVideo->setFigure(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Discussions>
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function addDiscussion(Discussions $discussion): self
    {
        if (!$this->discussions->contains($discussion)) {
            $this->discussions[] = $discussion;
            $discussion->setFigure($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussions $discussion): self
    {
        if ($this->discussions->removeElement($discussion)) {
            // set the owning side to null (unless already changed)
            if ($discussion->getFigure() === $this) {
                $discussion->setFigure(null);
            }
        }

        return $this;
    }
    
    /**
     * Recovering the image for the figure
     *
     * @return string
     */
    public function getPathImage(): ?string
    {
        $figure_image = self::PATH_IMAGE . 'default-tricks.jpg';

        $figuresImages = $this->getFiguresImages();
        foreach ($figuresImages as $path_image) {
            $figure_image = self::PATH_IMAGE . $path_image->getFilePath();
        }

        $this->setPathImage($figure_image);

        return $this->path_image;
    }

    private function setPathImage(string $path_image): self
    {
        $this->path_image = $path_image;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UsersRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity("email", message = "L'email {{ value }} est deja utilisé")
 * @UniqueEntity("user_name", message = "Le pseudo {{ value }} est deja utilisé")
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180)
     *
     * @Assert\Email(
     *     message = "L'email {{ value }} n'est pas valide"
     * )
     *
     * @Assert\NotNull(
     *     message = "L'email est obligatoire"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [
        "ROLE" => "ROLE_USER"
    ];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     *
     * @Assert\NotNull(
     *     message = "Le mot de passe est obligatoire"
     * )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotNull(
     *     message = "Le pseudo est obligatoire"
     * )
     *
     * @Assert\Length(
     *      min = 10,
     *      max = 20,
     *      minMessage = "Le pseudo doit contenir minimum {{ limit }} caractéres",
     *      maxMessage = "Le pseudo doit contenir maximum {{ limit }} caractéres"
     * )
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotNull(
     *     message = "La photo de profil est obligatoire"
     * )
     */
    private $file_path;

    /**
     * @ORM\Column(type="text")
     */
    private $token;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validate = false;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=Figures::class, mappedBy="user", orphanRemoval=true)
     */
    private $figures;

    /**
     * @ORM\OneToMany(targetEntity=Discussions::class, mappedBy="user", orphanRemoval=true)
     */
    private $discussions;

    public function __construct()
    {
        $this->figures = new ArrayCollection();
        $this->discussions = new ArrayCollection();

        date_default_timezone_set('Europe/Paris');
        $this->created_at = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->user_name;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->user_name;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getFilePath(): ?string
    {
        return $this->file_path;
    }

    public function setFilePath(string $file_path): self
    {
        $this->file_path = $file_path;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function isIsValidate(): ?bool
    {
        return $this->is_validate;
    }

    public function setIsValidate(bool $is_validate): self
    {
        $this->is_validate = $is_validate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Figures>
     */
    public function getFigures(): Collection
    {
        return $this->figures;
    }

    public function addFigure(Figures $figure): self
    {
        if (!$this->figures->contains($figure)) {
            $this->figures[] = $figure;
            $figure->setUser($this);
        }

        return $this;
    }

    public function removeFigure(Figures $figure): self
    {
        if ($this->figures->removeElement($figure)) {
            // set the owning side to null (unless already changed)
            if ($figure->getUser() === $this) {
                $figure->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Discussions>
     */
    public function getDiscussions(): Collection
    {
        return $this->discussions;
    }

    public function addDiscussion(Discussions $discussion): self
    {
        if (!$this->discussions->contains($discussion)) {
            $this->discussions[] = $discussion;
            $discussion->setUser($this);
        }

        return $this;
    }

    public function removeDiscussion(Discussions $discussion): self
    {
        if ($this->discussions->removeElement($discussion)) {
            // set the owning side to null (unless already changed)
            if ($discussion->getUser() === $this) {
                $discussion->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/FiguresType.php
<?php

namespace App\Form;

use App\Entity\Figures;
use App\Entity\FiguresGroups;
use App\Form\FiguresImagesType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class FiguresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la figure',
                'required' => true
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Déscription',
                'required' => true
            ])
            ->add('figure_group', EntityType::class, [
                'label' => 'Catégories',
                'class' => FiguresGroups::class,
                'choice_label' => 'name',
                'required' => true
            ])
            ->add('figuresImages', CollectionType::class, [
                'label' => false,
                'entry_type' => FiguresImagesType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('figuresVideos', CollectionType::class, [
                'label' => false,
                'entry_type' => FiguresVideosType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Enregistrer'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Figures::class
        ]);
    }
}

templates/figures/create.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ title }} d'une figure {% endblock %}

{% block body %}
<div class="my-5 py-2">
    <h1 class='text-center'>{{ title }}</h1>

    {% for message in app.flashes('errors_file') %}
    <div class="text-center my-5">
        <div class="alert alert-danger d-inline">
            {{ message }}
        </div>
    </div>
    {% endfor %}

    <div class="d-flex flex-column justify-content-center align-items-center">
        <div>
            {{ form_start(formFigures, {'attr': {'novalidate': 'novalidate', 'style' : 'width:450px'}}) }}

                <div class="error_image alert alert-danger text-center my-3">{{ form_errors(formFigures) }}</div>

                {{ form_row(formFigures.name) }}
                {{ form_row(formFigures.description) }}
                {{ form_row(formFigures.figure_group) }}
                <div class="d-flex align-items-center">
                    <p class="me-3">Images<p>
                    <button type="button" class="add_item_link_images btn btn-success" data-collection-holder-class="figuresImages">Ajouter</button>
                </div>
                <ul style="list-style-type:none;" class="figuresImages" data-index="{{ formFigures.figuresImages|length > 0 ? formFigures.figuresImages|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(formFigures.figuresImages.vars.prototype)|e('html_attr') }}">
                    {% for image in formFigures.figuresImages %}
                        <p class="file_name"> {{ image.vars.value.filePath }} </p>
                        <li class='d-flex align-items-start'>{{ form_row(image.file) }}</li>
                    {% endfor %}
                </ul>

                <div class="d-flex align-items-center">
                    <p class="me-3">Videos<p>
                    <button type="button" class="add_item_link_video btn btn-success" data-collection-holder-class="figuresVideos">Ajouter</button>
                </div>
                <ul style="list-style-type:none;" class="figuresVideos" data-index="{{ formFigures.figuresVideos|length > 0 ? formFigures.figuresVideos|last.vars.name + 1 : 0 }}" data-prototype="{{ form_widget(formFigures.figuresVideos.vars.prototype)|e('html_attr') }}">
                    {% for video in formFigures.figuresVideos %}
                        <li class='d-flex align-items-start'>{{ form_row(video.site_url) }}</li>
                    {% endfor %}
                </ul>

                {{ form_row(formFigures.save, {'attr': {'class': 'btn btn-primary d-block m-auto'}}) }}
            {{ form_end(formFigures) }}
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('javascript/FormFiguresVideos.js') }}"></script>
    <script src="{{ asset('javascript/FormFiguresImages.js') }}"></script>
{% endblock %}

templates/figures/figure.html.twig
{% extends 'base.html.twig' %}

{% block title %}Figure{% endblock %}

{% block body %}
    <div class="container mt-5">  
        <div class="d-flex justify-content-center mt-5">   
            <div class="col-sm-10 col-sm-offset-1 mt-5 mb-4 shadow rounded">  
                <div class="card position-relative">
                    <img class="card-img-top" src="{{ figure.PathImage }}" alt="figure snowboard">
                    <h1 class="familly-text position-absolute top-50 start-50 translate-middle bg-black text-white text-center rounded fs-2 fw-bolder p-3">
                        {{ figure.name|capitalize }}
                    </h1>
                </div>

                <div class='btn btn-info m-auto d-block d-sm-none mt-5 text-white fw-bolder' id="btnViewMedia" style="width:200px">Afficher les médias</div>

                <div class='d-none d-sm-block' id="containerViewMedia">
                    <div class='d-flex justify-content-around align-items-start flex-wrap'>
                        {% for image in figure.FiguresImages %}
                            <img src="{{ path_image_figure }}\{{ image.FilePath }}" width="300" class="m-4 rounded shadow">
                        {% endfor %}
                    </div>
                    <div class='d-flex justify-content-evenly align-items-start flex-wrap'>
                        {% for image in figure.FiguresVideos %}
                            <iframe class="m-4 rounded shadow" width="300" src="https://www.youtube.com/embed/{{ image.SiteUrl }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        {% endfor %}
                    </div>
                </div>

                <hr class='my-5 border border-dark mx-5'>

                <div class="lh-lg">
                    <h3 class="mb-5 text-center familly-text fs-2 fw-bolder">{{ figure.name|capitalize }}</h3>
                    <p class="px-4 familly-desc fs-6">{{ figure.description|nl2br }}</p>
                </div>

                <hr class='my-5 border border-dark mx-5'>

                <div class='d-flex justify-content-evenly align-items-center mt-5 flex-wrap'>
                    <div class="familly-desc fw-bolder border border-secondary px-3 py-2 rounded bg-black text-white mb-2">
                        Par : {{ figure.User.userName }}
                    </div>
                    <div class="familly-desc fw-bolder border border-secondary px-3 py-2 rounded bg-black text-white mb-2">
                        Ajouté le : {{ figure.CreatedAt|date("m/d/Y") }}
                        {% if figure.UpdatedAt %}
                        (Mise à jour le : {{ figure.UpdatedAt|date("m/d/Y") }})
                        {% endif %}
                    </div>
                    <div class="familly-desc fw-bolder border border-secondary px-3 py-2 rounded bg-black text-white">
                        Catégorie : {{ figure.FigureGroup.name }}
                    </div>
                </div>

                <hr class='my-5 border border-dark mx-5'>

                {% if app.user %}
                    <div class="px-5">
                        {{ form_start(formDiscussions, {'attr': {'novalidate': 'novalidate'}}) }}
                            {{ form_row(formDiscussions.content) }}
                            {{ form_row(formDiscussions.send, {'attr': {'class': 'btn btn-success d-block m-auto px-4 py-2'}}) }}
                        {{ form_end(formDiscussions) }}
                    </div>
                {% else %}
                <div class="d-flex justify-content-center align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="#EC7063" class="bi bi-exclamation-diamond" viewBox="0 0 16 16">
                        <path d="M6.95.435c.58-.58 1.52-.58 2.1 0l6.515 6.516c.58.58.58 1.519 0 2.098L9.05 15.565c-.58.58-1.519.58-2.098 0L.435 9.05a1.482 1.482 0 0 1 0-2.098L6.95.435zm1.4.7a.495.495 0 0 0-.7 0L1.134 7.65a.495.495 0 0 0 0 .7l6.516 6.516a.495.495 0 0 0 .7 0l6.516-6.516a.495.495 0 0 0 0-.7L8.35 1.134z"/>
                        <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                    </svg>
                    <div class='familly-desc fw-bolder ms-3 text-decoration-underline' style="color:#EC7063">Vous devre étre connecté pour pouvoir commenter</div>
                </div>
                {% endif %}

                <hr class='my-5 border border-dark mx-5'>

                <div class="py-2 rounded text-black fs-4 text-center">
                    {{ figure.Discussions|length }} Commentaire{% if figure.Discussions|length > 1 %}s{% endif %}
                </div>

                <div id="discussionsContent">
                    {% for discussion in figure.Discussions|reverse %}
                    <div class='d-flex p-4 rounded my-4 align-items-center d-none'>
                        <div class="me-3 d-flex flex-column text-center">
                            <img src="{{ path_image_profil }}\{{ discussion.User.FilePath }}" width="50" class="rounded-circle">
                        </div>
                        <div class='border border-black w-100 rounded p-4 position-relative'>
                            <div class="familly-desc fw-bolder bg-white border-2 text-black border border-secondary d-inline px-3 py-2 position-absolute top-0 start-50 translate-middle">
                                {{ discussion.User.UserName|capitalize }}
                            </div>
                            <div class="familly-desc">
                                {{ discussion.content|nl2br }}
                            </div>
                            <div class='familly-desc position-absolute bottom-0 end-0 pe-1 fs-6 fw-lighter text-muted'>
                                Publié le : {{ discussion.createdAt|date('m/d/Y à h:m') }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>

                {% if figure.Discussions|length > 10 %}
                    <div class="w-100 text-center mb-5">
                        <a class="text-black text-decoration-none" id="loadMoreDiscussions" style="cursor:pointer;">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#7DCEA0" class="bi bi-plus-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                            </svg>
                        </a>
                    </div>
                {% endif %}
            </div>     
        </div>           
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('javascript/FigureIndex.js') }}"></script>
{% endblock %}